---
title: "dissertation (brief) analyses"
author: "kat"
date: "1/26/2022"
output: html_document
---

# Preliminary stuff

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lme4)
library(readxl)


dat <- read_excel("dissertation - anon.xlsx")
```



## Overall Analyses {.tabset}

### Overall, Inclusive

```{r}
overall_inclusive_slope <- glmer(inclusive ~ questiontype * fragcode + (1 + questiontype | experimenter), dat, binomial)

summary(overall_inclusive_slope)
```


### Overall, Inclusive, no slope

```{r}
overall_inclusive <- glmer(inclusive ~ questiontype * fragcode + (1 | experimenter), dat, binomial)
summary(overall_inclusive)
```


### Inclusive Model Comparison
```{r}
anova(overall_inclusive, overall_inclusive_slope)
```


## Reliability {.tabset}

### Overall

```{r}
overall_sh1_noprep <- dat %>%
  select(experimenter, round, questiontype, inclusive, splithalf) %>%
  filter(splithalf == 1, questiontype == 'noprep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

overall_sh1_prep <- dat %>%
  select(experimenter, round, questiontype, inclusive, splithalf) %>%
  filter(splithalf == 1, questiontype == 'prep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

overall_sh2_noprep <- dat %>%
  select(experimenter, round, questiontype, inclusive, splithalf) %>%
  filter(splithalf == 2, questiontype == 'noprep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

overall_sh2_prep <- dat %>%
  select(experimenter, round, questiontype, inclusive, splithalf) %>%
  filter(splithalf == 2, questiontype == 'prep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

overall_sh1_difference <- overall_sh1_prep$meanresponse - overall_sh1_noprep$meanresponse

overall_sh2_difference <- overall_sh2_prep$meanresponse - overall_sh2_noprep$meanresponse


cor.test(overall_sh1_difference, overall_sh2_difference)
```


### Across rounds

```{r}
r1_noprep <- dat %>% 
  select(experimenter, round, questiontype, close, inclusive) %>%
  filter(round == 1, questiontype == 'noprep') %>%
  group_by(experimenter) %>%
   summarise(meanresponse = mean(inclusive, na.rm=TRUE))

r1_prep <- dat %>% 
  select(experimenter, round, questiontype, close, inclusive) %>%
  filter(round == 1, questiontype == 'prep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

r2_noprep <- dat %>% 
  select(experimenter, round, questiontype, close, inclusive) %>%
  filter(round == 2, questiontype == 'noprep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

r2_prep <- dat %>% 
  select(experimenter, round, questiontype, close, inclusive) %>%
  filter(round == 2, questiontype == 'prep') %>%
  group_by(experimenter) %>%
  summarise(meanresponse = mean(inclusive, na.rm = TRUE))

r1_difference <- r1_prep$meanresponse - r1_noprep$meanresponse

r2_difference <- r2_prep$meanresponse - r2_noprep$meanresponse


cor.test(r1_difference, r2_difference)
```



# Plot correlation for split half difference
```{r}

test_scatter <- data.frame(overall_sh1_difference, overall_sh2_difference)

splithalfplot <- ggplot(test_scatter, aes(overall_sh1_difference, overall_sh2_difference)) +
  geom_point(size = 2) +
  labs(title = "Split-Half Reliablity", x = "Split-Half 1 Priming Effect", y = "Split-Half 2 Priming Effect") +
  theme(
    axis.line = element_line(colour = "black"),
    axis.title.x = element_text(color = "black", size = 12), 
    axis.title.y = element_text(color = "black", size = 12),
    axis.text.x = element_text(color = "black", size = 12), 
    axis.text.y = element_text(color = "black", size = 12),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.title = element_text(color = "black", size = 12, face = "bold", hjust = 0.5)
  )

ggsave("splithalfplot.jpeg", plot=splithalfplot, width = 6, height = 4)
```